export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";

export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_PRODUCT_DETAILS_START = "GET_PRODUCT_DETAILS_START";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAILURE = "GET_PRODUCT_DETAILS_FAILURE";

export const GET_USER_CART_START = "GET_USER_CART_START";
export const GET_USER_CART_SUCCESS = "GET_USER_CART_SUCCESS";
export const GET_USER_CART_FAILURE = "GET_USER_CART_FAILURE";

export const ADD_CART_ITEM_START = "ADD_CART_ITEM_START";
export const ADD_CART_ITEM_SUCCESS = "ADD_CART_ITEM_SUCCESS";
export const ADD_CART_ITEM_FAILURE = "ADD_CART_ITEM_FAILURE";

export const DELETE_CART_START = "DELETE_CART_START";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_FAILURE = "DELETE_CART_FAILURE";
